services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/test
      - SPRING_REDIS_HOST=redis
    depends_on:
      - mariadb
      - redis
  mariadb:
    image: mariadb:10.5
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
      - MYSQL_USER=test-user
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
